### PR TITLE
fix: added minimal svg icons for admin page (#1429)

### PR DESCRIPTION
**Pull request by ghost**
Added new icons for admin page in zanata-server
Please test

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-ui/1)

### CODE REVIEW

**Comment by alex-sl-eng** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-ui/1)_

**Comment by alex-sl-eng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-ui/1#-:-KUEhZqBvQMhdxRORuGi:bnfp4nl)_

**Comment by ghost** [comment]
@aeng Should I merge and close this?

**Comment by ghost** [comment]
Closing because this has been merged in with another branch

**Pull request closed without merging**
